config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get "login" => "static_pages#login"

  devise_for :users, path: 'users', controllers: {sessions: "users/sessions"}
  devise_for :managers, path: 'managers', controllers: {sessions: "managers/sessions"}

  resources :staffs
  resources :projects
  resources :tasks
  resources :project_managers
  resources :task_managers
  resources :timesheets
  resources :roles
  resources :messages

  api_version(module: "V1", path: {value: "v1"}, default: true) do
    resources :users, defaults: {format: :json}
    resources :authen_user_tokens, only: :index, defaults: {format: :json}
    resources :projects, defaults: {format: :json}
    resources :tasks, defaults: {format: :json}
    resources :messages, default: {format: :json}
    resources :managers, default: {format: :json}
    resources :timesheets, default: {format: :json}
    resources :screenshots, default: {format: :json}
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :load_user, only: [:update, :destroy]
  before_action :check_email, only: :create

  def index
    @users = User.of_manager current_manager.id
    @roles = Role.of_manager current_manager.id
  end

# update user profile
  def update
    if @user.update_attributes user_params
      flash[:success] = "Cập nhật thông tin nhân viên thành công!"
    else
      flash[:danger] = "Cập nhật thông tin nhân viên thất bại!"
    end
    redirect_to staffs_path
  end

  def new
    @user = User.new
    @roles = Role.of_manager current_manager.id
  end

  def create
    user = User.new new_user_params
    user.authentication_token = Devise.friendly_token
    if user.save
      flash[:success] = "Tạo thành công nhân viên " + params[:user][:name]
    else
      flash[:danger] = "Tạo nhân viên thất bại!"
    end
    redirect_to new_staff_path
  end

  def destroy
    if @user.projects.present? || @user.tasks.present? || @user.timesheets.present?
      flash[:danger] = "Chỉ có thể xóa nhân viên khi nhân viên chưa tham gia dự án, chưa phân công task và chưa có timesheets nào."
    else
      @user.destroy
      flash[:success] = "Đã xóa thành công nhân viên #{@user.name}"
    end
    redirect_to staffs_path
  end

  private
  def new_user_params
    params.require(:user).permit(:name, :email, :password, :avatar, :gender,
      :status, :address, :birthday, :time_scr, :role_id).merge manager_id: current_manager.id,
      password_confirmation: params[:user][:password]
  end

  def user_params
    params.require(:user).permit :name, :address, :birthday, :gender, :avatar,
      :status, :time_scr, :role_id
  end

  def load_user
    @user = User.find_by id: params[:id]
    unless @user.present?
      flash[:danger] = "Không tìm thấy nhân viên này!"
      redirect_to staffs_path
    end
  end

  def check_email
    @user = User.new new_user_params
    @roles = Role.of_manager current_manager.id
    user = User.find_by email: params[:user][:email]
    manager = Manager.find_by email: params[:user][:email]
    if user.present? || manager.present?
      flash[:danger] = "Email này đã tồn tại, vui lòng chọn email khác"
      render :new
    end
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
  def load_status staff
    if staff.active?
      label_tag "stattus", "Hoạt động", class: "btn btn-success btn-xs"
    else
      label_tag "stattus", "Khóa", class: "btn btn-warning btn-xs"
    end
  end
end

app/views/staffs/_user.html.erb
<tr class="user-item">
  <td><%= image_tag user.avatar.present? ? user.avatar : "avatar-default", class: "user-avatar" %></td>
  <td><%= user.name %></td>
  <td><%= l(user.birthday) if user.birthday.present? %></td>
  <td><%= user.role.name %></td>
  <td><%= user.gender? ? "Nữ" : "Nam" %></td>
  <td><%= l user.created_at, format: "%d/%m/%Y" %></td>
  <td><%= load_status user %></td>
  <td class="td-actions text-right">
    <button type="button" rel="tooltip" title="" class="btn-user-edit btn
      btn-success btn-simple btn-xs btn-show-modal"
      data-original-title="Chỉnh sửa thông tin" data-toggle="modal" href="#edit-user-<%= user.id %>"
      data-id="<%= user.id %>">
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      <div class="ripple-container"></div>
    </button>
    <button type="button" rel="tooltip" title="" class="btn btn-primary btn-simple btn-xs"
     data-original-title="Chi tiết">
      <i class="fa fa-user-circle-o" aria-hidden="true"></i>
    </button>
    <%= link_to staff_path(user.id), method: :delete, class: "btn btn-danger btn-simple",
      "data-original-title": "Xóa nhân viên", rel: "tooltip", "data-confirm": "Bạn có chắc chắn xóa???" do %>
      <i class="fa fa-user-times" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

<!-- model edit profile user -->
<%= form_for user, url: staff_path(user.id), method: :put do |f| %>
<div class="modal fade" id="edit-user-<%= user.id %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Chỉnh sửa thông tin cá nhân</h4>
      </div>
      <div class="modal-body">
        <div class="card">
          <div class="card-content">
            <div class="col-md-9">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Email</label>
                    <%= f.text_field :email, class: "form-control", disabled: "" %>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Tên</label>
                    <%= f.text_field :name, class: "form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-9">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Sinh nhật</label>
                    <%= f.text_field :birthday, format: "%d/%m/%Y", class: "date form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group label-floating is-empty">
                    <%= f.check_box :gender %>
                    <label> Nữ</label>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Địa chỉ</label>
                    <%= f.text_field :address, class: "form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Thời gian chụp màn hình</label>
                    <%= f.number_field :time_scr, min:5, max: 120, class: "form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group label-floating is-empty">
                    <label style="font-size: 11px;">Trạng thái</label>
                    <%= f.select :status, options_for_select([["Hoạt động", :active],
                      ["Khóa", :locked]],
                      user.status), {},
                      class: "form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group label-floating is-empty">
                    <label>Chức vụ</label>
                      <%= f.select :role_id, @roles.collect{|r| [r.name, r.id]}, {},
                    class: "form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group label-floating is-empty">
                  <label class="text-center">Chọn hình mới</label>
                    <%= image_tag user.avatar.present? ? user.avatar : "avatar-default", class: "edit-user-avatar" %>
                    <%= f.file_field :avatar, accept: "image/jpeg, image/gif, image/png",
                    class: "upload-img hidden-file" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Hủy", "javascript:", class: "btn btn-default", "data-dismiss": "modal" %>
        <%= f.submit "Hoàn Tất", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/staffs/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="purple">
          <h4 class="title">DANH SÁCH NHÂN VIÊN</h4>
          <p class="category">Xem thông tin cá nhân, thông tin công việc, cập nhật profile...</p>
        </div>
        <div class="card-content table-responsive">
          <div class="material-datatables">
             <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
              <thead class="text-primary">
                <tr>
                  <th></th>
                  <th>Tên</th>
                  <th>Sinh nhật</th>
                  <th>Chức vụ</th>
                  <th>Giới tính</th>
                  <th>Ngày tạo</th>
                  <th>Trạng thái</th>
                  <th>Chức năng</th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "user", collection: @users %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/staffs/new.html.erb
<%= form_for @user, url: staffs_path do |f| %>
  <div class="card">
    <div class="card-header" data-background-color="purple">
      <h4 class="title">Thêm nhân viên mới</h4>
      <p class="category"></p>
    </div>
    <div class="card-content">
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group label-floating is-empty">
              <label class="control-label">Email</label>
              <%= f.email_field :email, required: true, class: "form-control" %>
              <span class="material-input"></span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="form-group label-floating is-empty">
              <label class="control-label">Tên</label>
              <%= f.text_field :name, maxlength: 100, minlength: 6, required: true, class: "form-control" %>
              <span class="material-input"></span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-9">
            <div class="form-group label-floating is-empty">
              <label class="control-label">Sinh nhật</label>
              <%= f.text_field :birthday, required: true, class: "date form-control" %>
              <span class="material-input"></span>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group label-floating is-empty">
              <%= f.check_box :gender %>
              <label> Nữ</label>
              <span class="material-input"></span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-8">
            <div class="form-group label-floating is-empty">
              <label class="control-label">Địa chỉ</label>
              <%= f.text_field :address, class: "form-control" %>
              <span class="material-input"></span>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group label-floating is-empty">
              <label class="control-label">Thời gian chụp màn hình</label>
              <%= f.number_field :time_scr, min:5, max: 120, class: "form-control" %>
              <span class="material-input"></span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group label-floating is-empty">
              <label>Trạng thái</label>
              <%= f.select :status, options_for_select([["Hoạt động", :active],
                ["Khoá", :locked]]), {}, class: "form-control" %>
              <span class="material-input"></span>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group label-floating is-empty">
              <label>Chức vụ</label>
              <%= f.select :role_id, @roles.collect{|r| [r.name, r.id]}, {},
                class: "form-control" %>
              <span class="material-input"></span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="form-group label-floating is-empty">
              <label class="control-label">Mật khẩu</label>
              <%= f.text_field :password, maxlength: 100, minlength: 6, required: true,
                type: "password", class: "form-control" %>
              <span class="material-input"></span>
            </div>
          </div>
        </div>
        <div>
          <%= f.submit "Tạo nhân viên", class: "btn btn-primary pull-right" %>
          <div class="clearfix"></div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group label-floating is-empty">
              <label class="text-center">Chọn hình mới</label>
              <%= image_tag "avatar-default",
              class: "edit-user-avatar" %>
              <%= f.file_field :avatar, accept: "image/jpeg, image/gif, image/png",
              class: "upload-img hidden-file" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>