config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get "login" => "static_pages#login"

  devise_for :users, path: 'users', controllers: {sessions: "users/sessions"}
  devise_for :managers, path: 'managers', controllers: {sessions: "managers/sessions"}

  resources :staffs
  resources :projects
  resources :tasks
  resources :project_managers
  resources :task_managers
  resources :timesheets
  resources :roles
  resources :messages

  api_version(module: "V1", path: {value: "v1"}, default: true) do
    resources :users, defaults: {format: :json}
    resources :authen_user_tokens, only: :index, defaults: {format: :json}
    resources :projects, defaults: {format: :json}
    resources :tasks, defaults: {format: :json}
    resources :messages, default: {format: :json}
    resources :managers, default: {format: :json}
    resources :timesheets, default: {format: :json}
    resources :screenshots, default: {format: :json}
  end
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_paranoid

  has_many :project_managers, dependent: :destroy
  has_many :time_sheets, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :users, through: :project_managers
  has_many :task_managers, through: :tasks

  belongs_to :manager

  enum status: {pending: 0, running: 1, delay: 2, finish: 3, cancel: 4}

  scope :of_manager, -> id {where manager_id: id}
  scope :for_update_status, -> {where status: [nil, 0, 1, 2]}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_manager!
  before_action :load_project, only: [:update, :show, :edit]

  def index
    @projects = Project.of_manager current_manager.id
  end

  def new
  end

  def edit
    case
    when params[:type] == Settings.update.finish
      if (@project.tasks.finish.size + @project.tasks.cancel.size) == @project.tasks.size
        if @project.update_attributes status: :finish, finish_date: Date.today
          flash[:success] = "Đã đánh dấu hoàn thành."
        else
          flash[:danger] = "Thất bại"
        end
      else
        flash[:danger] = "Không thể đánh dấu hoàn thành khi vẫn còn #{@project.tasks.size - @project.tasks.finish.size + @project.tasks.cancel.size} công việc chưa được hoàn thành."
      end
    when params[:type] == Settings.update.cancel
      if @project.update_attributes status: :cancel, finish_date: Date.today
        flash[:success] = "Hủy thành công."
      else
        flash[:danger] = "Thất bại"
      end
    end
    redirect_to project_path(@project.id)
  end

  def show

    @user_projects = ProjectManager.of_project(@project.id)
    @users_not_project = User.not_ids @user_projects.map(&:user_id)
    @tasks = @project.tasks
    @task_managers = TaskManager.by_ids @tasks.map(&:id)
  end

  def update
    if @project.update_attributes project_params
      flash[:success] = "Cập nhật thông tin dự án thành công!"
    else
      flash[:danger] = "Cập nhật thông tin dự án thất bại!"
    end
    redirect_to projects_path
  end

  def create
      project = Project.new new_project_params
    if project.save
      flash[:success] = "Tạo thành công dự án: " + project.name
    else
      flash[:danger] = "Tạo dự án thất bại!"
    end
    redirect_to new_project_path
  end

  private
  def new_project_params
    params.require(:project).permit(:name, :info, :start_date, :deadline).merge manager_id: current_manager.id
  end

  def project_params
    params.require(:project).permit :name, :info, :start_date, :deadline
  end

  def load_project
    @project = Project.find_by id: params[:id]
    unless @project.present?
      flash[:danger] = "Không tìm thấy dự án."
      redirect_to projects_path
    end
  end
end

app/controllers/v1/projects_controller.rb
class V1::ProjectsController < V1::BaseController
  def index
    resuft = current_user.projects.first
    if resuft.present?
      response_success t("api.success"), resuft
    else
      response_not_found  "Không có project nào"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def check_btn_finish_project project
    unless (project.tasks.finish.size + project.tasks.cancel.size) == project.tasks.size
      return "disabled"
    end
  end
end

app/views/projects/_list_task_managers.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header" data-background-color="<%= load_color_header @project %>">
      <h4 class="title">PHÂN CÔNG CÔNG VIỆC</h4>
    </div>
    <div class="card-content table-responsive">
      <div class="material-datatables">
        <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
          <thead class="text-primary">
            <tr>
              <th>Tên task</th>
              <th>Nhân viên</th>
              <th>Ghi chú</th>
              <th>Bắt đầu</th>
              <th>Deadline</th>
              <th>Hoàn thành</th>
              <th>Trạng thái</th>
              <th>Chức năng</th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "task_manager", collection: @task_managers %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/_list_tasks.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header" data-background-color="<%= load_color_header @project %>">
      <h4 class="title">DANH SÁCH CÔNG VIỆC</h4>
    </div>
    <div class="card-content table-responsive">
      <div class="material-datatables">
        <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
          <thead class="text-primary">
            <tr>
              <th>Tên</th>
              <th>Mô tả</th>
              <th>Bắt đầu</th>
              <th>Deadline</th>
              <th>Hoàn thành</th>
              <th>Nhân viên</th>
              <th>Trạng thái</th>
              <th>Chức năng</th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "task", collection: @tasks %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- model new task -->
<%= form_for Task.new, url: tasks_path do |f| %>
<%= f.hidden_field :project_id, value: @project.id %>
<div class="modal fade" id="modal-new-task">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Thêm công việc mới mới</h4>
      </div>
      <div class="modal-body">
        <div class="card">
          <div class="card-content">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Tên</label>
                    <%= f.text_field :name, maxlength: 3000, minlength: 6, required: true,
                      class: "form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Mô tả</label>
                    <%= f.text_area :info, maxlength: 3000, minlength: 6, class: "form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>

              <div class="row">
                <%= hidden_field "", "", data: {start: l(@project.start_date),
                  end: l(@project.deadline), name: "dự án"}, class: "limit-time" %>
                <div class="col-md-6">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Thời gian bắt đầu</label>
                    <%= f.text_field :start_date, required: true, class: "date date-start A1 form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group label-floating is-empty">
                    <label class="control-label">Deadline</label>
                    <%= f.text_field :deadline, required: true, class: "date date-end A2 form-control" %>
                    <span class="material-input"></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Hủy", "javascript:", class: "btn btn-default", "data-dismiss": "modal" %>
        <%= f.submit "Thêm", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/projects/_list_users.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header" data-background-color="<%= load_color_header @project %>">
      <h4 class="title">DANH SÁCH NHÂN VIÊN CỦA DỰ ÁN</h4>
    </div>
    <div class="card-content table-responsive">
      <div class="material-datatables">
        <table id="datatables" class="table table-striped table-no-bordered table-hover"
          cellspacing="0" width="100%" style="width:100%">
          <thead class="text-primary">
            <tr>
              <th>Tên</th>
              <th>Sinh nhật</th>
              <th>Ngày tham gia dự án</th>
              <th>Chức vụ</th>
              <th>Task đã nhận</th>
              <th>Task hoàn thành</th>
              <th>Task hủy</th>
              <th>Chức năng</th>
            </tr>
          </thead>
          <tbody>
            <% @user_projects.each do |item| %>
            <tr>
              <td><%= item.user.name %></td>
              <td><%= l item.user.birthday %></td>
              <td><%= l item.created_at, format: "%d/%m/%Y" %></td>
              <td><%= item.user.role.name %></td>
              <td><%= item.user.task_managers.size %></td>
              <td><%= item.user.task_managers.finish.size %></td>
              <td><%= item.user.task_managers.cancel.size %></td>
              <td>
                <%= link_to  project_manager_path(item.id, project_id: @project.id), method: :delete,
                  type: "button", rel: "tooltip", class: "btn btn-danger btn-simple",
                  "data-original-title": "Xóa nhân viên ra khỏi dự án" do %>
                  <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- model add user for project -->
<div class="modal fade" id="modal-add-user">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Thêm nhân viên vào dự án</h4>
      </div>
      <div class="modal-body">
        <div class="card">
          <div class="card-content">
            <div class="col-md-12">
              <table id="datatables" class="table table-striped table-no-bordered table-hover"
                cellspacing="0" width="100%" style="width:100%">
                <thead class="text-primary">
                  <tr>
                    <th>Tên</th>
                    <th>Chức vụ</th>
                    <th>Chức năng</th>
                  </tr>
                </thead>
                <tbody>
                  <% @users_not_project.each do |user| %>
                    <tr>
                      <td><%= user.name %></td>
                      <td><%= user.role.name %></td>
                      <td><%= link_to "Thêm", project_managers_path(project_id: @project.id,
                      user_id: user.id), method: :post %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_task.html.erb
<tr class="user-item">
  <td><%= task.name %></td>
  <td><%= task.info %></td>
  <td><%= l task.start_date %></td>
  <td><%= l task.deadline %></td>
  <td><%= task.finish_date.present? ? l(task.finish_date) : "--/--/----" %></td>
  <td><%= task.users.size %></td>
  <td><%= load_status_model task %></td>
  <td class="td-actions text-right">
    <button type="button" rel="tooltip" title="" class="<%= check_btn_edit task %>
      btn-user-edit btn btn-info btn-simple btn-xs btn-show-modal" data-original-title="
      Chỉnh sửa thông tin" data-toggle="modal" href="#edit-task-<%= task.id %>">
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      <div class="ripple-container"></div>
    </button>
    <button type="button" rel="tooltip" title="" class="<%= check_btn_edit task %>
      btn btn-success btn-simple btn-xs btn-show-modal btn-user-edit" data-original-title="Phân công"
      href="#new-task-manager-<%= task.id %>" data-toggle="modal">
     <i class="fa fa-user-plus" aria-hidden="true"></i>
    </button>
    <%= link_to edit_task_path(id: task.id, type: Settings.update.finish, project_id: @project.id),
      type: "button", rel: "tooltip", class: "#{check_btn_finish task}
      btn btn-primary btn-simple", "data-original-title": "Đánh dấu hoàn thành" do %>
      <i class="fa fa-check" aria-hidden="true"></i>
    <% end %>
    <%= link_to edit_task_path(id: task.id, type: Settings.update.cancel, project_id: @project.id),
      type: "button", rel: "tooltip", class: "#{check_btn_finish task}
      btn btn-warning btn-simple", "data-original-title": "Hủy công việc" do %>
      <i class="fa fa-ban" aria-hidden="true"></i>
    <% end %>
    <%= link_to task_path(task.id, project_id: @project.id), method: :delete,
      type: "button", rel: "tooltip", class: "#{check_btn_delete task}
      btn btn-danger btn-simple", "data-original-title": "Xóa" do %>
      <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

<% unless task.finish? || task.cancel? %>
  <!-- model edit task -->
  <%= form_for task, url: task_path(task.id), method: :put do |f| %>
    <div class="modal fade" id="edit-task-<%= task.id %>">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Chỉnh sửa công việc</h4>
          </div>
          <div class="modal-body">
            <div class="card">
              <div class="card-content">
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Tên</label>
                        <%= f.text_field :name, maxlength: 3000, minlength: 6, required: true,
                          class: "form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Mô tả</label>
                        <%= f.text_area :info, maxlength: 3000, minlength: 6, class: "form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <%= hidden_field "", "", data: {start: l(@project.start_date),
                      end: l(@project.deadline), name: "dự án"}, class: "limit-time" %>
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Thời gian bắt đầu</label>
                        <%= f.text_field :start_date, required: true, class: "date date-start form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Deadline</label>
                        <%= f.text_field :deadline, required: true, class: "date date-end form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <%= link_to "Hủy", "javascript:", class: "btn btn-default", "data-dismiss": "modal" %>
            <%= f.submit "Hoàn tất", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <!-- model new task manager -->
  <%= form_for TaskManager.new, url: task_managers_path(project_id: @project.id) do |f| %>
    <%= f.hidden_field :task_id, value: task.id %>
    <div class="modal fade" id="new-task-manager-<%= task.id %>">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Phân công công việc</h4>
          </div>
          <div class="modal-body">
            <div class="card">
              <div class="card-content">
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Tên</label>
                          <%= text_field_tag :name, task.name, disabled: "",
                          class: "form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Mô tả</label>
                        <%= f.text_area :note, maxlength: 3000, minlength: 6, class: "form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <%= hidden_field "", "", data: {start: l(task.start_date),
                      end: l(task.deadline), name: "công việc"}, class: "limit-time" %>
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Thời gian bắt đầu</label>
                        <%= f.text_field :start_date, required: true, class: "date date-start form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Deadline</label>
                        <%= f.text_field :deadline, required: true, class: "date date-end form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12">
                     <div class="form-group label-floating is-empty">
                      <label>Nhân viên</label>
                      <%= f.select :user_id, @user_projects.collect{|pm|
                        [pm.user.name + " - " + pm.user.role.name, pm.user.id]}, {},
                      class: "form-control" %>
                      <span class="material-input"></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <%= link_to "Hủy", "javascript:", class: "btn btn-default", "data-dismiss": "modal" %>
            <%= f.submit "Hoàn tất", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/projects/_task_manager.html.erb
<tr class="user-item">
  <td><%= task_manager.task.name %></td>
  <td><%= task_manager.user.name %></td>
  <td><%= task_manager.note %></td>
  <td><%= l task_manager.start_date %></td>
  <td><%= l task_manager.deadline %></td>
  <td><%= task_manager.finish_date.present? ? l(task_manager.finish_date) : "--/--/----" %></td>
  <td><%= load_status_model task_manager %></td>
  <td class="td-actions text-right">
    <button type="button" rel="tooltip" class="<%= check_btn_edit task_manager %>
      btn-user-edit btn btn-info btn-simple btn-show-modal" data-original-title="
      Chỉnh sửa thông tin" data-toggle="modal" href="#edit-task-manager-<%= task_manager.id %>">
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      <div class="ripple-container"></div>
    </button>
    <%= link_to edit_task_manager_path(id: task_manager.id,
      type: Settings.update.finish, project_id: @project.id),
      type: "button", rel: "tooltip", class: "#{check_btn_finish task_manager}
      btn btn-primary btn-simple", "data-original-title": "Đánh dấu hoàn thành" do %>
      <i class="fa fa-check" aria-hidden="true"></i>
    <% end %>
    <%= link_to edit_task_manager_path(id: task_manager.id,
      type: Settings.update.cancel, project_id: @project.id),
      type: "button", rel: "tooltip", class: "#{check_btn_finish task_manager}
      btn btn-warning btn-simple", "data-original-title": "Hủy công việc" do %>
      <i class="fa fa-ban" aria-hidden="true"></i>
    <% end %>
    <%= link_to  task_manager_path(task_manager.id, project_id: @project.id),
      method: :delete, type: "button", rel: "tooltip", class: "#{check_btn_delete task_manager}
      btn btn-danger btn-simple", "data-original-title": "Xóa" do %>
      <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

<% unless task_manager.finish? || task_manager.cancel? %>
  <!-- model edit task -->
  <%= form_for task_manager, url: task_manager_path(id: task_manager.id, project_id: @project.id), method: :put do |f| %>
    <div class="modal fade" id="edit-task-manager-<%= task_manager.id %>">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Chỉnh sửa công việc</h4>
          </div>
          <div class="modal-body">
            <div class="card">
              <div class="card-content">
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Tên</label>
                          <%= text_field_tag :name, task_manager.task.name, disabled: "",
                          class: "form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Mô tả</label>
                        <%= f.text_area :note, maxlength: 3000, minlength: 6, class: "form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <%= hidden_field "", "", data: {start: l(task_manager.task.start_date),
                      end: l(task_manager.task.deadline), name: "công việc"}, class: "limit-time" %>
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Thời gian bắt đầu</label>
                        <%= f.text_field :start_date, required: true, class: "date date-start form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group label-floating is-empty">
                        <label class="control-label">Deadline</label>
                        <%= f.text_field :deadline, required: true, class: "date date-end form-control" %>
                        <span class="material-input"></span>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12">
                     <div class="form-group label-floating is-empty">
                      <label>Nhân viên</label>
                      <%= f.select :user_id, @user_projects.collect{|pm|
                        [pm.user.name + " - " + pm.user.role.name, pm.user.id]}, {},
                      class: "form-control", disabled: "" %>
                      <span class="material-input"></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <%= link_to "Hủy", "javascript:", class: "btn btn-default", "data-dismiss": "modal" %>
            <%= f.submit "Hoàn tất", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="purple">
          <h4 class="title">DANH SÁCH DỰ ÁN</h4>
          <p class="category">Xem thông tin Dự Án</p>
        </div>
        <div class="card-content table-responsive">
          <div class="material-datatables">
             <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
              <thead class="text-primary">
                <tr>
                  <th>Tên</th>
                  <th>Mô tả</th>
                  <th>Ngày bắt đầu</th>
                  <th>Deadline</th>
                  <th>Trạng thái</th>
                  <th>Chức năng</th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "project", collection: @projects %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="title-project">
      <%= @project.name %>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header" data-background-color="<%= load_color_header @project %>">
          <h4 class="title">THÔNG TIN DỰ ÁN</h4>
        </div>
        <div class="card-content table-responsive">
          <div class="material-datatables">
             <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
               <tbody>
                <tr>
                  <td>Tên:</td>
                  <td><%= @project.name %></td>
                </tr>
                <tr>
                  <td>Mô tả:</td>
                  <td><%= @project.info %></td>
                </tr>
                <tr>
                  <td>Ngày bắt đầu:</td>
                  <td><%= @project.start_date %></td>
                </tr>
                <tr>
                  <td>Deadline:</td>
                  <td><%= @project.deadline %></td>
                </tr>
                <tr>
                  <td>Hoàn thành/Hủy:</td>
                  <td><%= @project.finish_date.present? ? @project.finish_date : "N/A" %></td>
                </tr>
                <tr>
                  <td>Trạng thái</td>
                  <td><%= load_status_model @project  %></td>
                </tr>
                <tr>
                  <td>Số thành viên</td>
                  <td><%= @project.users.size %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header" data-background-color="<%= load_color_header @project %>">
          <h4 class="title">THÔNG TIN CÔNG VIỆC</h4>
        </div>
        <div class="card-content table-responsive">
          <div class="material-datatables">
             <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
               <tbody>
                <tr>
                  <td>Tổng số công việc:</td>
                  <td><%= @project.tasks.size %></td>
                </tr>
                <tr>
                  <td>Số công việc chưa bắt đầu:</td>
                  <td><%= @project.tasks.pending.size %></td>
                </tr>
                <tr>
                  <td>Số công việc đang làm:</td>
                  <td><%= @project.tasks.running.size %></td>
                </tr>
                <tr>
                  <td>Số công việc chậm tiến độ:</td>
                  <td><%= @project.tasks.delay.size %></td>
                </tr>
                <tr>
                  <td>Số công việc đã hoàn thành:</td>
                  <td><%= @project.tasks.finish.size %></td>
                </tr>
                <tr>
                  <td>Số công việc hủy: </td>
                  <td><%= @project.tasks.cancel.size %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12 padding-bt-20">
      <%= link_to "Thêm nhân viên cho dự án", "#modal-add-user", "data-toggle": "modal",
        class: "#{check_btn_edit @project} btn btn-primary form-group margin-0 btn-show-modal" %>
      <%= link_to "Thêm công việc mới", "#modal-new-task", "data-toggle": "modal",
        class: "#{check_btn_edit @project} btn btn-primary form-group margin-0 btn-show-modal" %>
      <%= link_to "Đánh dấu hoàn thành", edit_project_path(@project.id, type: "finish"),
        class: "#{check_btn_edit @project} #{check_btn_finish_project @project}
        btn btn-primary form-group margin-0" %>
      <%= link_to "Hủy dự án", edit_project_path(@project.id, type: "cancel"),
        class: "#{check_btn_edit @project} btn btn-primary form-group margin-0" %>
    </div>
    <%= render "list_users" %>
    <%= render "list_tasks" %>
    <%= render "list_task_managers" %>
  </div>
</div>