config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get "login" => "static_pages#login"

  devise_for :users, path: 'users', controllers: {sessions: "users/sessions"}
  devise_for :managers, path: 'managers', controllers: {sessions: "managers/sessions"}

  resources :staffs
  resources :projects
  resources :tasks
  resources :project_managers
  resources :task_managers
  resources :timesheets
  resources :roles
  resources :messages

  api_version(module: "V1", path: {value: "v1"}, default: true) do
    resources :users, defaults: {format: :json}
    resources :authen_user_tokens, only: :index, defaults: {format: :json}
    resources :projects, defaults: {format: :json}
    resources :tasks, defaults: {format: :json}
    resources :messages, default: {format: :json}
    resources :managers, default: {format: :json}
    resources :timesheets, default: {format: :json}
    resources :screenshots, default: {format: :json}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manager.rb
class Manager < ApplicationRecord

  devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :users
  has_many :roles
  has_many :projects
  has_many :messages , as: :fromtable

  scope :of_manager, -> manager_id {where manager_id: manager_id}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :fromable, polymorphic: true

  enum status: {noseen: 0, seen: 1}

  scope :desc, ->{order created_at: :desc}

  scope :htd, -> email {where to: email}

  def user
    User.find_by id: self.fromtable_id
  end

  def manager
    Manager.find_by id: self.fromtable_id
  end

  def user_mail
    User.find_by email: self.to
  end

  def manager_mail
    Manager.find_by email: self.to
  end
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_paranoid

  has_many :project_managers, dependent: :destroy
  has_many :time_sheets, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :users, through: :project_managers
  has_many :task_managers, through: :tasks

  belongs_to :manager

  enum status: {pending: 0, running: 1, delay: 2, finish: 3, cancel: 4}

  scope :of_manager, -> id {where manager_id: id}
  scope :for_update_status, -> {where status: [nil, 0, 1, 2]}
end

app/models/project_manager.rb
class ProjectManager < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  belongs_to :project

  scope :of_project, -> project_id {where project_id: project_id}
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  belongs_to :manager

  scope :of_manager, -> id {where manager_id: id}
end

app/models/screenshot.rb
class Screenshot < ApplicationRecord
  belongs_to :timesheet

  mount_base64_uploader :image, ScreenshotUploader
end

app/models/task.rb
class Task < ApplicationRecord
  acts_as_paranoid

  has_many :task_managers
  has_many :users, through: :task_managers

  belongs_to :project

  enum status: {pending: 0, running: 1, delay: 2, finish: 3, cancel: 4}

  scope :for_update_status, -> {where status: [nil, 0, 1, 2]}
  scope :of_project, -> project_id {where project_id: project_id}
end

app/models/task_manager.rb
class TaskManager < ApplicationRecord
  acts_as_paranoid

  belongs_to :task
  belongs_to :user

  enum status: {pending: 0, running: 1, delay: 2, finish: 3, cancel: 4}

  scope :for_update_status, -> {where status: [nil, 0, 1, 2]}
  scope :by_ids, -> ids {where task_id: ids}
  scope :of_user, -> user_id {where user_id: user_id}
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  has_many :screenshots, dependent: :destroy

  belongs_to :project
  belongs_to :user

  scope :by_project_id, -> id {where project_id: id}
  scope :by_user_id, -> id {where user_id: id}
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :project_managers
  has_many :projects, through: :project_managers
  has_many :messages, dependent: :destroy
  has_many :timesheets
  has_many :task_managers
  has_many :tasks, through: :task_managers
  has_many :messages , as: :fromtable

  belongs_to :manager
  belongs_to :role

  enum status: {active: 0, locked: 1}

  mount_uploader :avatar, AvatarUploader

  scope :of_manager, -> id {where manager_id: id}
  scope :not_ids, -> ids {where.not id: ids}

  def add_authentication_token
    self.update_attributes authentication_token: generate_authentication_token
  end

  private
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token if User.where(authentication_token: token).count.zero?
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :load_role, only: [:update, :destroy]

  def index
    @roles = current_manager.roles
  end

  def create
    role = Role.new role_params
    if role.save
      flash[:success] = "Tạo thành công chức vụ #{role.name}"
    else
      flash[:danger] = "Không thể tạo chức vụ."
    end
    redirect_to roles_path
  end

  def update
    if @role.update_attributes role_edit_params
      flash[:success] = "Cập nhật thành công."
    else
      flash[:danger] = "Cập nhật thất bại."
    end
    redirect_to roles_path
  end

  def destroy
    if @role.users.size > 0
      flash[:danger] = "Không thể xóa chức vụ #{@role.name} vì nó có #{@role.users.size} nhân viên."
    else
      if @role.destroy
        flash[:success] = "Xóa thành công chức vụ #{@role.name}."
      else
        flash[:danger] = "Xóa không thành công"
      end
    end
    redirect_to roles_path
  end

  private
  def role_params
    params.require(:role).permit(:name, :info).merge manager_id: current_manager.id
  end

  def role_edit_params
    params.require(:role).permit :name, :info
  end

  def load_role
    @role = Role.find_by id: params[:id]
    unless @role.present?
      flash[:danger] = "Không tim thấy chức vụ."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def load_status_model item
    case
    when item.pending?
      label_tag "stattus", "Chưa bắt đầu", class: "btn btn-info btn-xs"
    when item.running?
      label_tag "stattus", "Đang diễn ra", class: "btn btn-success btn-xs"
    when item.delay?
      label_tag "stattus", "Chậm tiến độ", class: "btn btn-warning btn-xs"
    when item.finish?
      label_tag "stattus", "Đã hoàn thành", class: "btn btn-primary btn-xs"
    when item.cancel?
      label_tag "stattus", "Đã hủy", class: "btn btn-danger btn-xs"
    end
  end

  def check_btn_edit item
    if item.finish? || item.cancel?
      return "disabled"
    end
  end

  def check_btn_delete item
    unless item.pending?
      return "disabled"
    end
  end

  def check_btn_finish object
    case
    when object.class.name == "Task"
      unless !object.pending? && !object.finish? && !object.cancel? && object.task_managers.size == (object.task_managers.finish.size + object.task_managers.cancel.size)
        return "disabled"
      end
    when object.class.name == "TaskManager"
      unless !object.pending? && !object.finish? && !object.cancel?
        return "disabled"
      end
    end
  end

  def load_color_header item
    case
    when item.pending?
      "blue"
    when item.running?
      "green"
    when item.delay?
      "orange"
    when item.finish?
      "purple"
    when item.cancel?
      "red"
    end
  end

  def total_timesheets timesheets
    count = 0
    timesheets.each do |t|
      count += (t.end - t.start)
    end
    count
  end
end

app/helpers/dasboards_helper.rb
module DasboardsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def load_status_mess message
    if message.noseen?
      label_tag "stattus", "Chưa xem", class: "btn btn-success btn-xs status-message"
    else
      label_tag "stattus", "Đã xem", class: "btn btn-info btn-xs status-message"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def check_btn_finish_project project
    unless (project.tasks.finish.size + project.tasks.cancel.size) == project.tasks.size
      return "disabled"
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
  def load_status staff
    if staff.active?
      label_tag "stattus", "Hoạt động", class: "btn btn-success btn-xs"
    else
      label_tag "stattus", "Khóa", class: "btn btn-warning btn-xs"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <nav class="pull-left">
    <ul>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <a href="http://duytan.edu.vn/">
          DuyTan University
        </a>
      </li>
      <li>
        <a href="http://kcntt.duytan.edu.vn/">
          Faculty of Information Technology

        </a>
      </li>
    </ul>
 </nav>
  <p class="copyright pull-right">
    © <script>document.write(new Date().getFullYear())</script><a href="http://fb.com/borie.dn">
      Thành Luân</a>, ĐỒ ÁN TỐT NGHIỆP - DuyTan University
  </p>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Ứng dụng quản lý dự án từ xa</a>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-tachometer" aria-hidden="true"></i>
          <p class="hidden-lg hidden-md">Dashboard</p>
        </a>
      </li>
      <!-- <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-comments-o" aria-hidden="true"></i>
          <span class="notification">5</span>
          <p class="hidden-lg hidden-md">Notifications</p>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Mike John responded to your email</a></li>
          <li><a href="#">You have 5 new tasks</a></li>
          <li><a href="#">You're now friend with Andrew</a></li>
          <li><a href="#">Another Notification</a></li>
          <li><a href="#">Another One</a></li>
        </ul>
      </li> -->
      <li>
        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-user" aria-hidden="true"></i>
          <p class="hidden-lg hidden-md">Profile</p>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Thông tin cá nhân</a></li>
          <li><%= link_to "Đăng xuất", destroy_manager_session_path, method: :delete, "data-confirm": "Bạn muốn đăng xuất???" %></li>
        </ul>
     </li>
   </ul>

   <form class="navbar-form navbar-right" role="search">
    <div class="form-group  is-empty">
      <input type="text" class="form-control" placeholder="Search">
      <span class="material-input"></span>
      <span class="material-input"></span></div>
      <button type="submit" class="btn btn-white btn-round btn-just-icon">
        <i class="fa fa-search" aria-hidden="true"></i><div class="ripple-container"></div>
      </button>
    </form>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_slidebar.html.erb
<div class="logo">
  <%= link_to "QLDA", root_path, class: "simple-text" %>
</div>

<div class="sidebar-wrapper">
  <ul class="nav">
    <li>
      <%= link_to root_path do %>
        <i class="fa fa-tachometer" aria-hidden="true"></i>
        <p>Thông tin tổng quát</p>
      <% end %>
    </li>
    <li>
      <a data-toggle="collapse" href="#pagesUsers">
        <i class="fa fa-users" aria-hidden="true"></i>
        <p>Quản lý nhân viên<b class="caret"></b></p>
      </a>
      <div class="collapse" id="pagesUsers">
        <ul class="nav">
          <li>
            <%= link_to "Thêm nhân viên mới", new_staff_path %>
          </li>
          <li>
            <%= link_to "Danh sách nhân viên", staffs_path %>
          </li>
        </ul>
      </div>
    </li>
    <li>
      <a data-toggle="collapse" href="#pagesProjects">
        <i class="fa fa-server" aria-hidden="true"></i>
        <p>Quản lý project<b class="caret"></b></p>
      </a>
      <div class="collapse" id="pagesProjects">
        <ul class="nav">
          <li>
            <%= link_to "Thêm dự án mới", new_project_path %>
          </li>
          <li>
            <%= link_to "Danh sách dự án", projects_path %>
          </li>
        </ul>
      </div>
    </li>
     <li>
      <%= link_to roles_path do %>
        <i class="fa fa-address-card" aria-hidden="true"></i>
        <p>Quản lý chức vụ</p>
      <% end %>
    </li>
    <li>
      <%= link_to timesheets_path do %>
        <i class="fa fa-calendar" aria-hidden="true"></i>
        <p>Quản lý timesheet</p>
      <% end %>
    </li>
    <li>
      <a data-toggle="collapse" href="#pagesMesages">
        <i class="fa fa-comments-o" aria-hidden="true"></i>
        <p>Quản lý message<b class="caret"></b></p>
      </a>
      <div class="collapse" id="pagesMesages">
        <ul class="nav">
          <li>
            <%= link_to "Gửi messages", new_message_path %>
          </li>
          <li>
            <%= link_to "Danh sách mesages", messages_path %>
          </li>
        </ul>
      </div>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QLDAServer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="sidebar" data-color="purple" data-image="/assets/img/sidebar-1.jpg" alt="rss feed">
        <%= render "layouts/slidebar" %>
      </div>
      <div class="main-panel">
        <nav class="navbar navbar-transparent navbar-absolute">
          <%= render "layouts/header" %>
        </nav>
        <div class="content content-body-right">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
        <footer class="footer">
          <%= render "layouts/footer"  %>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QLDAServer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>